-- RLS policies, helper functions, and auth bootstrap trigger for FridgeMind.
-- Hand-written (not generated by `prisma migrate diff`) since Prisma's schema has no
-- representation of RLS/functions/triggers — this is expected/normal for Prisma+Supabase.
--
-- Household/role rules implemented here follow CLAUDE.md §5 ("Роли в household"):
--   - Household-scoped access via a helper that resolves the caller's own household_id/role
--     from public.users, keyed by auth.uid() (avoids the recursive-RLS trap of a policy on
--     `users` subquerying `users` directly).
--   - recipes/recipe_steps/recipe_ingredients/meal_slots/menu_weeks/menu_days/menu_day_meals
--     writable only by ORGANIZER/EDITOR.
--   - pantry_items/shopping_list_items/shopping_list_item_meals writable by all roles.
--   - ingredients is a global catalog (no household_id) — readable/insertable by anyone
--     authenticated, grows organically.
--   - households/users role-management writes (renaming household, regenerating invite
--     code, changing another member's role, removing a member) restricted to ORGANIZER.

-- ============================================================================
-- Helper functions
-- ============================================================================

create or replace function public.current_household_id()
returns text
language sql
security definer
stable
set search_path = ''
as $$
  select household_id from public.users where id = auth.uid()::text
$$;

create or replace function public.current_household_role()
returns public.household_role
language sql
security definer
stable
set search_path = ''
as $$
  select role from public.users where id = auth.uid()::text
$$;

-- ============================================================================
-- households
-- ============================================================================

alter table public.households enable row level security;

create policy "households_select_own" on public.households for select to authenticated
  using ( id = public.current_household_id() );

create policy "households_update_organizer" on public.households for update to authenticated
  using ( id = public.current_household_id() and public.current_household_role() = 'ORGANIZER' )
  with check ( id = public.current_household_id() and public.current_household_role() = 'ORGANIZER' );

-- No INSERT policy: households are only ever created by handle_new_user (SECURITY DEFINER,
-- bypasses RLS as the function owner). No DELETE policy: household deletion is out of MVP scope.

-- ============================================================================
-- users
-- ============================================================================

alter table public.users enable row level security;

create policy "users_select_household" on public.users for select to authenticated
  using ( household_id = public.current_household_id() );

create policy "users_update_self" on public.users for update to authenticated
  using ( id = auth.uid()::text )
  with check ( id = auth.uid()::text );
-- Known limitation (documented, not solved at the RLS layer here): this is row-level, not
-- column-level, so a MEMBER could technically UPDATE their own role/household_id via a raw
-- request. Per CLAUDE.md §9 ("RLS-политики/server actions" — either is acceptable), the
-- column-level restriction is deferred to the server-action layer that already has role-check
-- TODOs in the API routes, rather than solved here.

create policy "users_update_by_organizer" on public.users for update to authenticated
  using ( household_id = public.current_household_id() and public.current_household_role() = 'ORGANIZER' )
  with check ( household_id = public.current_household_id() and public.current_household_role() = 'ORGANIZER' );

create policy "users_delete_self" on public.users for delete to authenticated
  using ( id = auth.uid()::text );
-- "At least one ORGANIZER must remain" (CLAUDE.md §5) is a cross-row business invariant that
-- RLS can't express — enforced in the future "leave household" server action, not here.

create policy "users_delete_by_organizer" on public.users for delete to authenticated
  using ( household_id = public.current_household_id() and public.current_household_role() = 'ORGANIZER' and id <> auth.uid()::text );

-- ============================================================================
-- ingredients (global catalog, no household_id — see CLAUDE.md §5)
-- ============================================================================

alter table public.ingredients enable row level security;

create policy "ingredients_select_authenticated" on public.ingredients for select to authenticated
  using ( true );

create policy "ingredients_insert_authenticated" on public.ingredients for insert to authenticated
  with check ( true );

-- No UPDATE/DELETE policy: catalog corrections are out of MVP scope (deny by default).

-- ============================================================================
-- recipes
-- ============================================================================

alter table public.recipes enable row level security;

create policy "recipes_select_household" on public.recipes for select to authenticated
  using ( household_id = public.current_household_id() );

create policy "recipes_insert_organizer_editor" on public.recipes for insert to authenticated
  with check ( household_id = public.current_household_id() and public.current_household_role() in ('ORGANIZER','EDITOR') );

create policy "recipes_update_organizer_editor" on public.recipes for update to authenticated
  using ( household_id = public.current_household_id() and public.current_household_role() in ('ORGANIZER','EDITOR') )
  with check ( household_id = public.current_household_id() and public.current_household_role() in ('ORGANIZER','EDITOR') );

create policy "recipes_delete_organizer_editor" on public.recipes for delete to authenticated
  using ( household_id = public.current_household_id() and public.current_household_role() in ('ORGANIZER','EDITOR') );

-- ============================================================================
-- recipe_steps (child of recipes)
-- ============================================================================

alter table public.recipe_steps enable row level security;

create policy "recipe_steps_select_household" on public.recipe_steps for select to authenticated
  using ( exists (
    select 1 from public.recipes r
    where r.id = recipe_steps.recipe_id and r.household_id = public.current_household_id()
  ) );

create policy "recipe_steps_insert_organizer_editor" on public.recipe_steps for insert to authenticated
  with check ( exists (
    select 1 from public.recipes r
    where r.id = recipe_steps.recipe_id and r.household_id = public.current_household_id()
      and public.current_household_role() in ('ORGANIZER','EDITOR')
  ) );

create policy "recipe_steps_update_organizer_editor" on public.recipe_steps for update to authenticated
  using ( exists (
    select 1 from public.recipes r
    where r.id = recipe_steps.recipe_id and r.household_id = public.current_household_id()
      and public.current_household_role() in ('ORGANIZER','EDITOR')
  ) )
  with check ( exists (
    select 1 from public.recipes r
    where r.id = recipe_steps.recipe_id and r.household_id = public.current_household_id()
      and public.current_household_role() in ('ORGANIZER','EDITOR')
  ) );

create policy "recipe_steps_delete_organizer_editor" on public.recipe_steps for delete to authenticated
  using ( exists (
    select 1 from public.recipes r
    where r.id = recipe_steps.recipe_id and r.household_id = public.current_household_id()
      and public.current_household_role() in ('ORGANIZER','EDITOR')
  ) );

-- ============================================================================
-- recipe_ingredients (child of recipes)
-- ============================================================================

alter table public.recipe_ingredients enable row level security;

create policy "recipe_ingredients_select_household" on public.recipe_ingredients for select to authenticated
  using ( exists (
    select 1 from public.recipes r
    where r.id = recipe_ingredients.recipe_id and r.household_id = public.current_household_id()
  ) );

create policy "recipe_ingredients_insert_organizer_editor" on public.recipe_ingredients for insert to authenticated
  with check ( exists (
    select 1 from public.recipes r
    where r.id = recipe_ingredients.recipe_id and r.household_id = public.current_household_id()
      and public.current_household_role() in ('ORGANIZER','EDITOR')
  ) );

create policy "recipe_ingredients_update_organizer_editor" on public.recipe_ingredients for update to authenticated
  using ( exists (
    select 1 from public.recipes r
    where r.id = recipe_ingredients.recipe_id and r.household_id = public.current_household_id()
      and public.current_household_role() in ('ORGANIZER','EDITOR')
  ) )
  with check ( exists (
    select 1 from public.recipes r
    where r.id = recipe_ingredients.recipe_id and r.household_id = public.current_household_id()
      and public.current_household_role() in ('ORGANIZER','EDITOR')
  ) );

create policy "recipe_ingredients_delete_organizer_editor" on public.recipe_ingredients for delete to authenticated
  using ( exists (
    select 1 from public.recipes r
    where r.id = recipe_ingredients.recipe_id and r.household_id = public.current_household_id()
      and public.current_household_role() in ('ORGANIZER','EDITOR')
  ) );

-- ============================================================================
-- pantry_items (all household roles can write)
-- ============================================================================

alter table public.pantry_items enable row level security;

create policy "pantry_items_all_household" on public.pantry_items for all to authenticated
  using ( household_id = public.current_household_id() )
  with check ( household_id = public.current_household_id() );

-- ============================================================================
-- meal_slots
-- ============================================================================

alter table public.meal_slots enable row level security;

create policy "meal_slots_select_household" on public.meal_slots for select to authenticated
  using ( household_id = public.current_household_id() );

create policy "meal_slots_insert_organizer_editor" on public.meal_slots for insert to authenticated
  with check ( household_id = public.current_household_id() and public.current_household_role() in ('ORGANIZER','EDITOR') );

create policy "meal_slots_update_organizer_editor" on public.meal_slots for update to authenticated
  using ( household_id = public.current_household_id() and public.current_household_role() in ('ORGANIZER','EDITOR') )
  with check ( household_id = public.current_household_id() and public.current_household_role() in ('ORGANIZER','EDITOR') );

create policy "meal_slots_delete_organizer_editor" on public.meal_slots for delete to authenticated
  using ( household_id = public.current_household_id() and public.current_household_role() in ('ORGANIZER','EDITOR') );

-- Note: the initial 3 default meal_slots per new household are created by handle_new_user
-- (SECURITY DEFINER, bypasses RLS) — the INSERT policy above covers ORGANIZER/EDITOR adding
-- more slots afterward.

-- ============================================================================
-- menu_weeks
-- ============================================================================

alter table public.menu_weeks enable row level security;

create policy "menu_weeks_select_household" on public.menu_weeks for select to authenticated
  using ( household_id = public.current_household_id() );

create policy "menu_weeks_insert_organizer_editor" on public.menu_weeks for insert to authenticated
  with check ( household_id = public.current_household_id() and public.current_household_role() in ('ORGANIZER','EDITOR') );

create policy "menu_weeks_update_organizer_editor" on public.menu_weeks for update to authenticated
  using ( household_id = public.current_household_id() and public.current_household_role() in ('ORGANIZER','EDITOR') )
  with check ( household_id = public.current_household_id() and public.current_household_role() in ('ORGANIZER','EDITOR') );

create policy "menu_weeks_delete_organizer_editor" on public.menu_weeks for delete to authenticated
  using ( household_id = public.current_household_id() and public.current_household_role() in ('ORGANIZER','EDITOR') );

-- ============================================================================
-- menu_days (child of menu_weeks)
-- ============================================================================

alter table public.menu_days enable row level security;

create policy "menu_days_select_household" on public.menu_days for select to authenticated
  using ( exists (
    select 1 from public.menu_weeks w
    where w.id = menu_days.menu_week_id and w.household_id = public.current_household_id()
  ) );

create policy "menu_days_insert_organizer_editor" on public.menu_days for insert to authenticated
  with check ( exists (
    select 1 from public.menu_weeks w
    where w.id = menu_days.menu_week_id and w.household_id = public.current_household_id()
      and public.current_household_role() in ('ORGANIZER','EDITOR')
  ) );

create policy "menu_days_update_organizer_editor" on public.menu_days for update to authenticated
  using ( exists (
    select 1 from public.menu_weeks w
    where w.id = menu_days.menu_week_id and w.household_id = public.current_household_id()
      and public.current_household_role() in ('ORGANIZER','EDITOR')
  ) )
  with check ( exists (
    select 1 from public.menu_weeks w
    where w.id = menu_days.menu_week_id and w.household_id = public.current_household_id()
      and public.current_household_role() in ('ORGANIZER','EDITOR')
  ) );

create policy "menu_days_delete_organizer_editor" on public.menu_days for delete to authenticated
  using ( exists (
    select 1 from public.menu_weeks w
    where w.id = menu_days.menu_week_id and w.household_id = public.current_household_id()
      and public.current_household_role() in ('ORGANIZER','EDITOR')
  ) );

-- ============================================================================
-- menu_day_meals (child of menu_days -> menu_weeks)
-- ============================================================================

alter table public.menu_day_meals enable row level security;

create policy "menu_day_meals_select_household" on public.menu_day_meals for select to authenticated
  using ( exists (
    select 1 from public.menu_days d join public.menu_weeks w on w.id = d.menu_week_id
    where d.id = menu_day_meals.menu_day_id and w.household_id = public.current_household_id()
  ) );

create policy "menu_day_meals_insert_organizer_editor" on public.menu_day_meals for insert to authenticated
  with check ( exists (
    select 1 from public.menu_days d join public.menu_weeks w on w.id = d.menu_week_id
    where d.id = menu_day_meals.menu_day_id and w.household_id = public.current_household_id()
      and public.current_household_role() in ('ORGANIZER','EDITOR')
  ) );

create policy "menu_day_meals_update_organizer_editor" on public.menu_day_meals for update to authenticated
  using ( exists (
    select 1 from public.menu_days d join public.menu_weeks w on w.id = d.menu_week_id
    where d.id = menu_day_meals.menu_day_id and w.household_id = public.current_household_id()
      and public.current_household_role() in ('ORGANIZER','EDITOR')
  ) )
  with check ( exists (
    select 1 from public.menu_days d join public.menu_weeks w on w.id = d.menu_week_id
    where d.id = menu_day_meals.menu_day_id and w.household_id = public.current_household_id()
      and public.current_household_role() in ('ORGANIZER','EDITOR')
  ) );

create policy "menu_day_meals_delete_organizer_editor" on public.menu_day_meals for delete to authenticated
  using ( exists (
    select 1 from public.menu_days d join public.menu_weeks w on w.id = d.menu_week_id
    where d.id = menu_day_meals.menu_day_id and w.household_id = public.current_household_id()
      and public.current_household_role() in ('ORGANIZER','EDITOR')
  ) );

-- MEMBER marks a meal "eaten" via public.mark_meal_eaten() (SECURITY DEFINER RPC, defined
-- below), not via a direct UPDATE — see that function's comment for the rationale.

-- ============================================================================
-- shopping_list_items (all household roles can write)
-- ============================================================================

alter table public.shopping_list_items enable row level security;

create policy "shopping_list_items_all_household" on public.shopping_list_items for all to authenticated
  using ( household_id = public.current_household_id() )
  with check ( household_id = public.current_household_id() );

-- ============================================================================
-- shopping_list_item_meals (child of shopping_list_items, all household roles)
-- ============================================================================

alter table public.shopping_list_item_meals enable row level security;

create policy "shopping_list_item_meals_all_household" on public.shopping_list_item_meals for all to authenticated
  using ( exists (
    select 1 from public.shopping_list_items i
    where i.id = shopping_list_item_meals.shopping_list_item_id and i.household_id = public.current_household_id()
  ) )
  with check ( exists (
    select 1 from public.shopping_list_items i
    where i.id = shopping_list_item_meals.shopping_list_item_id and i.household_id = public.current_household_id()
  ) );

-- ============================================================================
-- Grants (PostgREST needs both RLS policies AND a role-level GRANT)
-- ============================================================================

grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant execute on all functions in schema public to authenticated;

-- ============================================================================
-- handle_new_user: bootstraps households/users/meal_slots on auth.users signup
-- ============================================================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_name text;
  v_invite_code text;
  v_household_id text;
  v_role public.household_role;
begin
  v_name := coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1));
  v_invite_code := new.raw_user_meta_data->>'inviteCode';

  if v_invite_code is not null then
    select id into v_household_id from public.households where invite_code = v_invite_code;
  end if;

  if v_household_id is null then
    insert into public.households (id, invite_code, created_at, updated_at)
    values (extensions.gen_random_uuid()::text, extensions.gen_random_uuid()::text, now(), now())
    returning id into v_household_id;

    insert into public.meal_slots (id, household_id, name, "order", created_at) values
      (extensions.gen_random_uuid()::text, v_household_id, 'Завтрак', 0, now()),
      (extensions.gen_random_uuid()::text, v_household_id, 'Обед',    1, now()),
      (extensions.gen_random_uuid()::text, v_household_id, 'Ужин',   2, now());

    v_role := 'ORGANIZER';
  else
    v_role := 'MEMBER';
  end if;

  insert into public.users (id, email, name, household_id, role, created_at, updated_at)
  values (new.id::text, new.email, v_name, v_household_id, v_role, now(), now());

  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Note: raw_user_meta_data is acceptable here only because it bootstraps membership at
-- signup time, not as an ongoing authorization source — every RLS policy above reads
-- public.users.role, never JWT claims. The "already in another household, replace" flow
-- (CLAUDE.md §6) applies to an already-authenticated user hitting an invite link, not a new
-- signup, and is a future server action/RPC, out of scope here.

-- ============================================================================
-- mark_meal_eaten: narrow RPC so MEMBER can mark a meal eaten without a broad UPDATE grant
-- ============================================================================

-- menu_day_meals otherwise follows the ORGANIZER/EDITOR-only write pattern, but CLAUDE.md §5
-- requires MEMBER be able to mark a meal eaten. Rather than loosening the general UPDATE
-- policy (which would also let MEMBER change recipe_id/servings/meal_slot_id), this RPC keeps
-- the blanket table policy strictly ORGANIZER/EDITOR at the cost of one extra function to
-- keep in sync with schema changes.
create or replace function public.mark_meal_eaten(p_menu_day_meal_id text, p_is_eaten boolean)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.menu_day_meals m
  set is_eaten = p_is_eaten,
      eaten_at = case when p_is_eaten then now() else null end,
      eaten_by_user_id = case when p_is_eaten then auth.uid()::text else null end
  from public.menu_days d
  join public.menu_weeks w on w.id = d.menu_week_id
  where m.id = p_menu_day_meal_id
    and m.menu_day_id = d.id
    and w.household_id = public.current_household_id();
end;
$$;

grant execute on function public.mark_meal_eaten(text, boolean) to authenticated;
